#!/usr/bin/env python3
"""Generate the catalog-derived documentation pages (deterministic, no timestamps).

    python3 tools/docs/generate.py            # write every generated page
    python3 tools/docs/generate.py --check    # exit 1 when a committed page is stale

Outputs
  docs/guides/component-ownership.md          from catalog/components.yaml + environments/profiles/*.yaml
  docs/guides/architecture-deployment-matrix.md
                                              from catalog/architecture-matrix.yaml + catalog/telemetry-capabilities.yaml
                                              + tools/docs/architecture-matrix-supplement.yaml (columns the catalog
                                              leaves empty, each value citing the README it was taken from)
  docs/runbooks/alerts/<service>.md           one page per rendered service in
                                              observability/onboarding/rendered/<env>/*.json: the monitors of that
                                              service grouped by runbook section (anchors match `#<section>`)
  README.md (block between the STATUS markers) catalog/component counts

Dependencies: Python 3.11+, PyYAML.
"""

from __future__ import annotations

import argparse
import glob
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
GENERATED = "<!-- GENERATED by tools/docs/generate.py - do not edit by hand; run `python3 tools/docs/generate.py` -->"
ENV = "dev"


def load(rel: str):
    return yaml.safe_load((REPO / rel).read_text())


def esc(text) -> str:
    return str(text if text is not None else "").replace("|", "\\|").replace("\n", " ").strip()


def code_list(items) -> str:
    return ", ".join(f"`{i}`" for i in items) if items else "-"


# --------------------------------------------------------------------------------------------- components
def profiles_by_component() -> dict[str, list[str]]:
    out: dict[str, list[str]] = defaultdict(list)
    for f in sorted((REPO / "environments/profiles").glob("*.yaml")):
        p = yaml.safe_load(f.read_text())
        for cid in p.get("components") or []:
            out[cid].append(p["profile"])
    return out


def root_files_present(comp: dict) -> str:
    path = REPO / comp["path"]
    if not path.exists():
        return "no"
    if comp["kind"] == "terraform":
        tf = {p.name for p in path.glob("*.tf")}
        logic = tf - {"backend.tf", "providers.tf", "versions.tf", "variables.tf", "variables-environment.tf", "outputs.tf"}
        tests = any(path.glob("tests/*.tftest.hcl"))
        if not logic:
            return "partial (no resource files yet)"
        return "yes" + ("" if tests else " (no tests/)")
    return "yes"


def render_component_ownership() -> str:
    reg = load("catalog/components.yaml")
    comps = reg["components"]
    producers = {c: comp["id"] for comp in comps for c in comp.get("produces") or []}
    profiles = profiles_by_component()
    lines = [
        GENERATED,
        "",
        "# Component ownership",
        "",
        "Every row is one entry of [`catalog/components.yaml`](../../catalog/components.yaml), the single source of truth for",
        "change detection, state boundaries, dependency order and the generated pipeline stages",
        "([ADR-0001](../architecture/ADR-0001-design-contract.md) sections 3-5). A component is the unit of change detection,",
        "state, planning and deployment: one Terraform root = one state file `<env>/<component-id>.tfstate`.",
        "",
        "Column meanings:",
        "",
        "* **Owner directory** - the only directory whose files belong to the component (shared Terraform modules are",
        "  discovered from `source = \"../...\"` and are code reuse, not ownership).",
        "* **Produces** - contract published to `contracts/<env>/<contract>/v1.json`; schema `catalog/contracts/<contract>.v1.schema.json`.",
        "* **Consumes** - contracts read as Terraform variables (`foundation-network` becomes `var.foundation_network`);",
        "  *optional* contracts are used when their producer is enabled.",
        "* **Depends on** - producers of the consumed contracts (hard ordering) plus the artifact builds whose digests the root",
        "  deploys. `obs-monitoring` additionally runs after every selected application deployment (`after_deployments`).",
        "* **Profiles** - `environments/profiles/<profile>.yaml` files that enable the component.",
        "* **Code present** - whether the owner directory contains resource files at generation time. It is *not* a",
        "  status claim; status per ADR section 11 is tracked in [IMPLEMENTATION_CHECKLIST.md](../IMPLEMENTATION_CHECKLIST.md).",
        "",
    ]
    by_layer: dict[str, list[dict]] = defaultdict(list)
    for comp in comps:
        by_layer[comp["layer"]].append(comp)
    counts = Counter(c["layer"] for c in comps)
    kinds = Counter(c["kind"] for c in comps)
    lines += [
        f"Registry: **{len(comps)} components** - "
        + ", ".join(f"{counts[l]} {l}" for l in ["bootstrap", "foundation", "platform", "observability", "applications", "docs"] if counts[l])
        + " (" + ", ".join(f"{kinds[k]} {k}" for k in sorted(kinds)) + ").",
        "",
    ]
    titles = {
        "bootstrap": "Bootstrap", "foundation": "Foundation", "platform": "Platform", "observability": "Observability (lab roots)",
        "applications": "Applications (artifact builds and deployment roots)", "docs": "Documentation",
    }
    for layer in ["bootstrap", "foundation", "platform", "observability", "applications", "docs"]:
        if layer not in by_layer:
            continue
        lines += [f"## {titles[layer]}", "",
                  "| Component | Kind | Owner directory | State key | Produces | Consumes | Optional consumes | Depends on | Profiles | Code present |",
                  "|---|---|---|---|---|---|---|---|---|---|"]
        for comp in by_layer[layer]:
            cid = comp["id"]
            kind = comp["kind"]
            if kind == "artifact":
                art = comp.get("artifact") or {}
                kind = f"artifact ({art.get('type')}" + (f" + {', '.join(art.get('also') or [])}" if art.get("also") else "") + ")"
            state = f"`<env>/{cid}.tfstate`" if comp["kind"] == "terraform" else "-"
            if comp.get("pipeline") == "manual":
                state += " (local first, then migrated)"
            deps = sorted({producers[c] for c in comp.get("consumes") or [] if c in producers} | set(comp.get("depends_on") or []))
            deps += [a for a in comp.get("artifacts") or []]
            if comp.get("after_deployments"):
                deps.append("(after all selected deploy-*)")
            optional = [c for c in comp.get("optional_consumes") or [] if c not in (comp.get("consumes") or [])]
            path = comp["path"]
            link = f"[`{path}/`](../../{path})"
            extra = []
            if comp.get("pipeline") == "manual":
                extra.append("pipeline: manual")
            if comp.get("discovers_resources"):
                extra.append("discovers resources from every enabled contract")
            kind_cell = kind + (f" - {'; '.join(extra)}" if extra else "")
            lines.append(
                f"| `{cid}` | {esc(kind_cell)} | {link} | {state} | {code_list(comp.get('produces'))} | {code_list(comp.get('consumes'))} | "
                f"{code_list(optional)} | {code_list(deps)} | {', '.join(sorted(profiles.get(cid, []))) or '-'} | {root_files_present(comp)} |"
            )
        lines.append("")
    lines += [
        "## Regenerate",
        "",
        "```bash",
        "python3 tools/docs/generate.py          # after editing catalog/components.yaml or a profile",
        "python3 tools/docs/generate.py --check  # CI-style staleness check",
        "python3 -m tools.changeset graph        # registry valid + acyclic, dependency layers",
        "```",
        "",
    ]
    return "\n".join(lines)


# ----------------------------------------------------------------------------------- architecture matrix
def _workload_service(w: str) -> str:
    return w.split(" ")[0].strip()


def data_for(workloads: list[str], databases: dict) -> list[str]:
    out = []
    for w in workloads:
        svc = _workload_service(w)
        for db_id, d in databases.items():
            owners = [(d.get("owner", ""), False)] + [(a, True) for a in d.get("also") or []]
            for o, is_also in owners:
                o_svc = str(o).split(" ")[0]
                if not o_svc or o_svc == "none":
                    continue
                if svc.endswith("*") and o_svc.startswith(svc.rstrip("*")):
                    continue  # wildcard adapters: summarised below
                if o_svc == svc:
                    paren = re.search(r"\(([^)]*)\)", str(o))
                    boundary = paren.group(1) if (is_also and paren) else d.get("boundary", "")
                    out.append(f"{db_id} ({boundary})")
        if svc.endswith("*"):
            out.append("one database family per adapter instance (see Databases below)")
    return sorted(set(out))


def render_architecture_matrix() -> str:
    m = load("catalog/architecture-matrix.yaml")
    tel = load("catalog/telemetry-capabilities.yaml")["compute"]
    sup = load("tools/docs/architecture-matrix-supplement.yaml")["architectures"]
    dbs = m["databases"]
    lines = [
        GENERATED,
        "",
        "# Architecture deployment matrix",
        "",
        "Rendered from [`catalog/architecture-matrix.yaml`](../../catalog/architecture-matrix.yaml) (deliberate",
        "architecture-to-workload mapping, no compute x database Cartesian product), the telemetry paths of",
        "[`catalog/telemetry-capabilities.yaml`](../../catalog/telemetry-capabilities.yaml) and, for columns the catalog leaves",
        "empty, [`tools/docs/architecture-matrix-supplement.yaml`](../../tools/docs/architecture-matrix-supplement.yaml)",
        "whose values are taken from the deployment-root READMEs (marked with a dagger, source linked per row).",
        "",
        "Nothing in this table has been deployed: the smoke and rollback procedures are implemented in code",
        "(`applications/deployments/scripts/*.sh`, `tools/smoke/smoke.py`) but have not run against Azure.",
        "",
        "## Messaging topology",
        "",
        "| Entity | Name | Consumer | Purpose |",
        "|---|---|---|---|",
    ]
    sb = m["messaging"]["service_bus"]
    for name, sub in sb["subscriptions"].items():
        lines.append(f"| subscription of topic `{sb['topic']}` | `{name}` | {esc(sub['consumer'])} | {esc(sub['purpose'])} |")
    for name, q in sb["queues"].items():
        lines.append(f"| queue | `{name}` | {esc(q['consumer'])} | producers: {esc(', '.join(q.get('producers') or []))} |")
    lines += [
        "",
        "## Compute architectures",
        "",
        "| Architecture | Workloads | Deployment root | Artifact | Runtime configuration | Data dependency | Logs | Traces / metrics | Smoke test | Rollback |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for arch, a in m["architectures"].items():
        s = sup.get(arch, {})
        t = (tel.get(arch) or {}).get("signals", {})
        dep = a.get("deployment")
        dep = dep if isinstance(dep, list) else ([dep] if dep else [])
        dep_cell = ", ".join(f"`{d}`" for d in dep) or "-"

        def col(key: str) -> str:
            if a.get(key):
                return esc(a[key])
            if s.get(key):
                return esc(s[key]) + " &dagger;"
            return "not specified"

        data = esc(a["data"]) if a.get("data") else esc("; ".join(data_for(a.get("workloads") or [], dbs)) or "none")
        logs = esc((t.get("app_logs") or {}).get("method", "-"))
        traces = esc((t.get("traces") or {}).get("method", "-"))
        name = arch
        if a.get("status_default"):
            name += f" (default: {a['status_default']})"
        if a.get("note"):
            name += f" - {a['note']}"
        src = s.get("source")
        rollback = col("rollback")
        if src:
            rollback += f" ([src](../../{src}))"
        lines.append(
            f"| `{esc(name)}` | {esc(', '.join(a.get('workloads') or []))} | {dep_cell} | {col('artifact')} | {col('runtime_config')} | "
            f"{data} | {logs} | {traces} | {col('smoke')} | {rollback} |"
        )
    conflicts = load("tools/docs/architecture-matrix-supplement.yaml").get("conflicts") or []
    if conflicts:
        lines += ["", "## Open inconsistencies between catalog and deployment code", "",
                  "These rows are rendered from the catalog as-is; the deployment code differs as described (reported to the owners).", ""]
        lines += [f"* `{esc(c['architecture'])}` - {esc(c['issue'])} (source: [{c['source']}](../../{c['source']}))" for c in conflicts]
    lines += [
        "",
        "## Databases (owner service and data boundary)",
        "",
        "| Database catalog entry | Owner | Boundary | Also used by | Default |",
        "|---|---|---|---|---|",
    ]
    for db_id, d in dbs.items():
        lines.append(f"| `{db_id}` | {esc(d.get('owner'))} | {esc(d.get('boundary', '-'))} | {esc(', '.join(d.get('also') or [])) or '-'} | {esc(d.get('default', 'per profile'))} |")
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------------------- alert runbooks
SECTION_INDEX = "../alert-response.md"


def render_alert_runbooks() -> dict[str, str]:
    pages: dict[str, str] = {}
    rendered = sorted(glob.glob(str(REPO / f"observability/onboarding/rendered/{ENV}/*.json")))
    index = [GENERATED, "", "# Alert runbooks per service", "",
             f"One page per service rendered from `observability/onboarding/rendered/{ENV}/*.json`. Each monitor message links to",
             "`<runbook_url>#<section>`; the anchors on these pages match those sections, and each section points to the shared",
             f"procedure in [alert-response.md]({SECTION_INDEX}).",
             "",
             "> The lab manifests (`observability/onboarding/<env>/*.yaml`) currently set `runbook_url` to",
             "> `https://runbooks.example.com/enterprise-hello/<service>` (a placeholder host). To make monitor links resolve to",
             "> these pages, the observability owner must point `metadata.runbook_url` at the published location of this",
             "> directory (see [known limitations](../../known-limitations.md#documentation-and-links)).",
             "",
             "| Service | Team | Runbook sections |", "|---|---|---|"]
    for f in rendered:
        d = json.loads(Path(f).read_text())
        svc = d.get("service") or Path(f).stem
        md = d.get("metadata") or {}
        monitors = d.get("monitors") or []
        if isinstance(monitors, dict):
            monitors = [dict(v, key=k) for k, v in monitors.items()]
        slos = d.get("slos") or []
        sections: dict[str, list[dict]] = defaultdict(list)
        for mon in monitors:
            url = mon.get("runbook_url") or ""
            sec = url.split("#", 1)[1] if "#" in url else mon.get("runbook_section", "")
            if sec:
                sections[sec].append(mon)
        raw = Path(f).read_text()
        base = md.get("runbook_url") or ""
        if base:
            for sec in set(re.findall(re.escape(base) + r"#([a-z0-9-]+)", raw)):
                sections.setdefault(sec, [])
        for slo in slos:
            for br in slo.get("burn_rate_alerts") or []:
                url = br.get("runbook_url") or ""
                if "#" in url:
                    sections[url.split("#", 1)[1]].append(dict(br, key=f"slo:{slo.get('name')}", type="slo alert"))
        team = md.get("team") or d.get("team") or "-"
        lines = [GENERATED, "", f"# Alert runbook: {svc}", "",
                 f"Service `{svc}` - team `{team}`, owner {md.get('owner') or d.get('owner') or '-'}, tier `{md.get('tier') or d.get('tier') or '-'}`,",
                 f"architecture `{(d.get('spec') or {}).get('architecture') or d.get('architecture') or '-'}`. Source: `observability/onboarding/{ENV}/{Path(f).stem}.yaml`",
                 f"(rendered `observability/onboarding/rendered/{ENV}/{Path(f).name}`).", "",
                 "Before acting on any no-data alert, check the telemetry pipeline canary ([telemetry-pipeline](telemetry-pipeline.md#pipeline-canary)):",
                 "a broken pipeline looks like silence.", ""]
        for sec in sorted(sections):
            lines += [f"## {sec}", "", f"Procedure: [alert-response.md#{sec}]({SECTION_INDEX}#{sec})", ""]
            mons = sections[sec]
            if mons:
                lines += ["| Monitor key | Name | Type | Severity |", "|---|---|---|---|"]
                for mon in sorted(mons, key=lambda x: str(x.get("key"))):
                    lines.append(f"| `{esc(mon.get('key'))}` | {esc(mon.get('name'))} | {esc(mon.get('type'))} | {esc(mon.get('severity') or mon.get('priority') or '-')} |")
                lines.append("")
            elif sec.startswith("slo"):
                lines += [f"SLO burn-rate alerts ({len(slos)} SLO(s) declared for this service).", ""]
        pages[f"docs/runbooks/alerts/{svc}.md"] = "\n".join(lines)
        index.append(f"| [{svc}]({svc}.md) | `{team}` | {', '.join(f'[{s}]({svc}.md#{s})' for s in sorted(sections))} |")
    index.append("")
    pages["docs/runbooks/alerts/README.md"] = "\n".join(index)
    return pages


# ----------------------------------------------------------------------------------- alert response
SECTION_ORDER = [
    "error-rate", "http-5xx", "latency", "missing-telemetry", "error-logs", "consumer-errors", "workflow-failures",
    "workflow-duration", "job-missed", "job-errors", "rum-errors", "rum-performance", "replicas-unavailable",
    "container-restarts", "aca-5xx", "aca-restarts", "appservice-5xx", "appservice-latency", "functions-5xx", "host-cpu",
    "aci-not-reporting", "logicapp-failed", "sql-cpu", "sql-connections", "sql-deadlocks", "sql-storage", "postgres-down",
    "postgres-cpu", "postgres-connections", "postgres-storage", "mysql-cpu", "mysql-connections", "mysql-storage",
    "cosmos-ru", "cosmos-availability", "storage-availability", "storage-latency", "queue-backlog", "queue-lag",
    "queue-dead-letter", "queue-errors", "eventhub-throttled", "redis-load", "redis-memory", "pipeline-canary",
    "fluentbit-errors", "fluentbit-dropped", "fluentbit-not-reporting", "otel-export", "otel-refused",
    "otel-not-reporting", "slo-burn-rate", "slo-availability", "slo-latency", "synthetics",
]

# Lab-specific notes (facts from the lab code/READMEs) appended to the archetype troubleshooting text.
LAB_NOTES = {
    "missing-telemetry": "Lab: ACA/ACI traces go to the OTel gateway (`obs-telemetry-transport`, internal ingress); AKS/VM traces to the "
                         "Datadog Agent on `$(DD_AGENT_HOST)` / `localhost:4317`. Check `OTEL_EXPORTER_OTLP_ENDPOINT` in the app settings "
                         "owned by the deployment root.",
    "error-logs": "Lab: logs carry `dd.trace_id`; use `GET /admin/faults` (with `X-Fault-Token`) to rule out an active fault injection "
                  "([fault-injection.md](fault-injection.md)).",
    "error-rate": "Lab: check active faults (`GET /admin/faults`), recent deployments (DORA events from the Evidence stage) and the "
                  "dependency monitors of the same service. Roll back per [rollback.md](rollback.md).",
    "http-5xx": "Lab: 503 problems from `/readyz`-gated dependencies mean a dependency is down; the BFF maps transport failures to "
                "504 `dependency-timeout`, 503 `dependency-unavailable` (circuit open), 502 `dependency-error`.",
    "consumer-errors": "Lab: consumers are hello-worker (`notifications`), hello-functions `audit`, hello-jobs `process-batch-items` "
                       "(`batch-items`). Poison messages go to the dead-letter queue by design.",
    "workflow-failures": "Lab: `hello.workflow.completed{workflow,outcome}` from hello-durable; `outcome:compensated` means payment failed "
                         "after a reservation (partner-sim failure/decline or `PAYMENT_TIMEOUT_SECONDS`). Inspect an instance with "
                         "`GET /api/workflows/order-<order_id>` on the durable app (private).",
    "workflow-duration": "Lab: OrderProcessing races `ChargePayment` (3 attempts) against a durable timer; partner-sim latency is "
                         "`LATENCY_MS_MEAN` + jitter.",
    "job-missed": "Lab: ACA jobs `seed` (manual), `reconcile` and `traffic` (scheduled), `batchitems` (event). "
                  "`az containerapp job execution list -n <job> -g <rg>`.",
    "rum-errors": "Lab: browser config comes from `config.json` written by `deploy-frontend`; `apiBaseUrl` pointing to "
                  "`https://api.invalid` means no API contract was available at deploy time; CORS errors mean the SWA origin "
                  "is missing from the BFF `cors_allowed_origins` (two-pass setting).",
    "pipeline-canary": "Lab: the canary is a Fluent Bit `dummy` input in the aggregator (`service:telemetry-canary`). When it alerts, "
                       "treat every application no-data alert in the same window as a pipeline problem. Check the aggregator "
                       "Container App replicas/logs and the `datadog-api-key` secret (rotation: [secret-rotation.md](secret-rotation.md)).",
    "otel-refused": "Lab: the gateway accepts OTLP logs and drops them on purpose (nop exporter); refused spans/metrics usually "
                    "mean memory limiter pressure - raise `gateway.memory` or replicas in `obs-telemetry-transport`.",
    "queue-backlog": "Lab: in the `minimal` profile the subscriptions `notifications`, `audit` and `archive` exist but have no consumer "
                     "deployed, so they accumulate until the 14-day TTL; disable `queue.*` for them or deploy the consumers.",
    "queue-dead-letter": "Lab: max delivery count 10 (subscriptions) / 5 (`batch-items`); dead-letter on expiry. Inspect with Service "
                         "Bus Explorer; poison messages are dead-lettered intentionally by hello-worker and hello-jobs.",
    "eventhub-throttled": "Lab: Event Hubs Standard 1 TU by default (`obs-telemetry-transport` `event_hub.capacity`, auto-inflate "
                          "optional). Diagnostic settings of every app write here.",
    "aci-not-reporting": "Lab: hello-partner-sim runs as a single ACI container group (restart policy Always); re-apply "
                         "`deploy-partner-sim` to recreate it.",
    "postgres-down": "Lab: PostgreSQL Flexible Server (B1ms) for `catalog`; a manually stopped server "
                     "shows here.",
    "sql-cpu": "Lab: S0 (`orders`), serverless 1 vCore (`fulfillment`, auto-pause 60 min), Basic (`adapter`).",
    "slo-burn-rate": "Open the SLO, then the service error/latency monitors; check recent deployments and dependency health.",
}

GENERIC = {
    "slo-availability": ("Availability SLO (metric-based: (hits - errors) / hits of `trace.http.server.request`).",
                         "1. Open the SLO and its burn-rate alerts.\n2. Follow the error-rate and http-5xx procedures above."),
    "slo-latency": ("Latency SLO (time-slice on the p95 of `trace.http.server.request` against `threshold_ms`).",
                    "1. Open the SLO.\n2. Follow the latency procedure above."),
    "slo-burn-rate": ("SLO burn-rate alert (`slo alert`): critical 1h/5m, warning 6h/30m window pairs.",
                      "1. Identify which SLO burns (availability or latency).\n2. Follow the matching procedure."),
    "synthetics": ("Synthetic API or browser test failed. Lab tests are created paused (`synthetics_paused = true`); private "
                   "endpoints run only from a configured private location.",
                   "1. Open the test result and the failing step/assertion.\n2. Compare with APM for the same window.\n"
                   "3. If only the synthetic fails, check DNS/ingress/private location reachability."),
}


def render_alert_response() -> str:
    by_section: dict[str, list[tuple[str, str, dict]]] = defaultdict(list)
    for f in sorted(glob.glob(str(REPO / "observability/archetypes/**/*.yaml"), recursive=True)):
        d = yaml.safe_load(Path(f).read_text()) or {}
        mons = d.get("monitors") or {}
        for key, m in mons.items():
            if isinstance(m, dict) and m.get("runbook_section"):
                by_section[m["runbook_section"]].append((key, str(Path(f).relative_to(REPO)), m))
    lines = [GENERATED, "", "# Alert response procedures", "",
             "One section per runbook anchor used by the monitors of the observability package. The summary and troubleshooting",
             "steps are taken verbatim from the archetypes (`observability/archetypes/**`, placeholders like `[[service]]` are filled",
             "per service in the rendered monitor message); **Lab** notes add facts specific to this repository. Per-service",
             "pages listing the actual monitors: [alerts/README.md](alerts/README.md).", "",
             "General first steps for every alert: (1) check the telemetry pipeline canary ([pipeline-canary](#pipeline-canary)) -",
             "a broken pipeline looks like silence; (2) check deployment events for the service in the last hour; (3) check active",
             "fault injections ([fault-injection.md](fault-injection.md)); (4) roll back if a release correlates ([rollback.md](rollback.md)).",
             "", "Sections: " + " ".join(f"[{s}](#{s})" for s in SECTION_ORDER), ""]
    extra = sorted(set(by_section) - set(SECTION_ORDER))
    for sec in SECTION_ORDER + extra:
        lines += [f"## {sec}", ""]
        mons = by_section.get(sec, [])
        if mons:
            seen_summary = set()
            for key, src, m in mons:
                summ = (m.get("summary") or "").strip()
                if summ and summ not in seen_summary:
                    seen_summary.add(summ)
                    lines += [f"**{summ}**", ""]
            lines.append("Monitors: " + ", ".join(f"`{k}` ({m.get('severity', '-')}, {src.split('/', 1)[1]})" for k, src, m in mons) + ".")
            lines.append("")
            seen_ts = set()
            for key, src, m in mons:
                ts = (m.get("troubleshooting") or "").strip()
                if ts and ts not in seen_ts:
                    seen_ts.add(ts)
                    lines += [ts, ""]
        elif sec in GENERIC:
            summ, ts = GENERIC[sec]
            lines += [f"**{summ}**", "", ts, ""]
        else:
            lines += ["No archetype monitor currently uses this section.", ""]
        if sec in LAB_NOTES:
            lines += [f"Lab: {LAB_NOTES[sec]}" if not LAB_NOTES[sec].startswith("Lab:") else LAB_NOTES[sec], ""]
    return "\n".join(lines)


# --------------------------------------------------------------------------------------- README status
def render_status_block() -> str:
    entries = []
    for f in sorted((REPO / "catalog/services").glob("*.yaml")):
        entries += yaml.safe_load(f.read_text())["services"]
    impl = Counter(e["status"]["implementation"] for e in entries)
    live = Counter(e["status"].get("live_validation", "not-run") for e in entries)
    nonga = sum(1 for e in entries if e["lifecycle"]["status"] != "ga")
    comps = load("catalog/components.yaml")["components"]
    kinds = Counter(c["kind"] for c in comps)
    layers = Counter(c["layer"] for c in comps)
    lines = [
        "<!-- BEGIN STATUS (generated by tools/docs/generate.py) -->",
        "| Catalog | Total | implemented | disabled | blocked | cataloged | live validation |",
        "|---|---:|---:|---:|---:|---:|---|",
        f"| Azure services (`catalog/services/*.yaml`) | {len(entries)} | {impl['implemented']} | {impl['disabled']} | {impl['blocked']} | {impl['cataloged']} | "
        + ", ".join(f"{k}: {v}" for k, v in sorted(live.items())) + " |",
        "",
        f"Components in `catalog/components.yaml`: **{len(comps)}** ({', '.join(f'{v} {k}' for k, v in sorted(kinds.items()))}; "
        + ", ".join(f"{v} {k}" for k, v in sorted(layers.items())) + f"). Non-GA lifecycle entries in the service catalog: {nonga}.",
        "<!-- END STATUS -->",
    ]
    return "\n".join(lines)


def outputs() -> dict[str, str]:
    out = {
        "docs/guides/component-ownership.md": render_component_ownership(),
        "docs/guides/architecture-deployment-matrix.md": render_architecture_matrix(),
    }
    out.update(render_alert_runbooks())
    out["docs/runbooks/alert-response.md"] = render_alert_response()
    readme = (REPO / "README.md")
    if readme.exists():
        text = readme.read_text()
        block = render_status_block()
        new = re.sub(r"<!-- BEGIN STATUS.*?<!-- END STATUS -->", lambda _: block, text, flags=re.S)
        out["README.md"] = new
    return {k: (v if v.endswith("\n") else v + "\n") for k, v in out.items()}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail when a committed output differs")
    args = ap.parse_args(argv)
    stale = []
    files = outputs()
    for rel, content in files.items():
        p = REPO / rel
        if args.check:
            if not p.exists() or p.read_text() != content:
                stale.append(rel)
        else:
            p.parent.mkdir(parents=True, exist_ok=True)
            if not p.exists() or p.read_text() != content:
                p.write_text(content)
                print(f"wrote {rel}")
    if args.check:
        alerts_dir = REPO / "docs/runbooks/alerts"
        for p in alerts_dir.glob("*.md"):
            rel = str(p.relative_to(REPO))
            if rel not in files:
                stale.append(f"{rel} (orphan)")
        for s in stale:
            print(f"STALE: {s}")
        return 1 if stale else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
