#!/usr/bin/env python3
"""Generate the catalog-derived documentation pages (deterministic, no timestamps).

    python3 tools/docs/generate.py            # write every generated page
    python3 tools/docs/generate.py --check    # exit 1 when a committed page is stale

Outputs
  docs/guides/component-ownership.md          from catalog/components.yaml + environments/profiles/*.yaml
  docs/guides/architecture-deployment-matrix.md
                                              from catalog/architecture-matrix.yaml + catalog/telemetry-capabilities.yaml
                                              + tools/docs/architecture-matrix-supplement.yaml (columns the catalog
                                              leaves empty, each value citing the README it was taken from)
  docs/runbooks/alerts/<service>.md           one page per rendered service in
                                              observability/onboarding/rendered/<env>/*.json: the monitors of that
                                              service grouped by runbook section (anchors match `#<section>`)
  README.md (block between the STATUS markers) catalog/component counts

Dependencies: Python 3.11+, PyYAML.
"""

from __future__ import annotations

import argparse
import glob
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
GENERATED = "<!-- GENERATED by tools/docs/generate.py - do not edit by hand; run `python3 tools/docs/generate.py` -->"
ENV = "dev"


def load(rel: str):
    return yaml.safe_load((REPO / rel).read_text())


def esc(text) -> str:
    return str(text if text is not None else "").replace("|", "\\|").replace("\n", " ").strip()


def code_list(items) -> str:
    return ", ".join(f"`{i}`" for i in items) if items else "-"


# --------------------------------------------------------------------------------------------- components
def profiles_by_component() -> dict[str, list[str]]:
    out: dict[str, list[str]] = defaultdict(list)
    for f in sorted((REPO / "environments/profiles").glob("*.yaml")):
        p = yaml.safe_load(f.read_text())
        for cid in p.get("components") or []:
            out[cid].append(p["profile"])
    return out


def root_files_present(comp: dict) -> str:
    path = REPO / comp["path"]
    if not path.exists():
        return "no"
    if comp["kind"] == "terraform":
        tf = {p.name for p in path.glob("*.tf")}
        logic = tf - {"backend.tf", "providers.tf", "versions.tf", "variables.tf", "variables-environment.tf", "outputs.tf"}
        tests = any(path.glob("tests/*.tftest.hcl"))
        if not logic:
            return "partial (no resource files yet)"
        return "yes" + ("" if tests else " (no tests/)")
    return "yes"


def render_component_ownership() -> str:
    reg = load("catalog/components.yaml")
    comps = reg["components"]
    producers = {c: comp["id"] for comp in comps for c in comp.get("produces") or []}
    profiles = profiles_by_component()
    lines = [
        GENERATED,
        "",
        "# Component ownership",
        "",
        "Every row is one entry of [`catalog/components.yaml`](../../catalog/components.yaml), the single source of truth for",
        "change detection, state boundaries, dependency order and the generated pipeline stages",
        "([ADR-0001](../architecture/ADR-0001-design-contract.md) sections 3-5). A component is the unit of change detection,",
        "state, planning and deployment: one Terraform root = one state file `<env>/<component-id>.tfstate`.",
        "",
        "Column meanings:",
        "",
        "* **Owner directory** - the only directory whose files belong to the component (shared Terraform modules are",
        "  discovered from `source = \"../...\"` and are code reuse, not ownership).",
        "* **Produces** - contract published to `contracts/<env>/<contract>/v1.json`; schema `catalog/contracts/<contract>.v1.schema.json`.",
        "* **Consumes** - contracts read as Terraform variables (`foundation-network` becomes `var.foundation_network`);",
        "  *optional* contracts are used when their producer is enabled.",
        "* **Depends on** - producers of the consumed contracts (hard ordering) plus the artifact builds whose digests the root",
        "  deploys. `obs-monitoring` additionally runs after every selected application deployment (`after_deployments`).",
        "* **Profiles** - `environments/profiles/<profile>.yaml` files that enable the component.",
        "* **Code present** - whether the owner directory contains resource files at generation time. It is *not* a",
        "  status claim; status per ADR section 11 is tracked in [IMPLEMENTATION_CHECKLIST.md](../IMPLEMENTATION_CHECKLIST.md).",
        "",
    ]
    by_layer: dict[str, list[dict]] = defaultdict(list)
    for comp in comps:
        by_layer[comp["layer"]].append(comp)
    counts = Counter(c["layer"] for c in comps)
    kinds = Counter(c["kind"] for c in comps)
    lines += [
        f"Registry: **{len(comps)} components** - "
        + ", ".join(f"{counts[l]} {l}" for l in ["bootstrap", "foundation", "platform", "observability", "applications", "docs"] if counts[l])
        + " (" + ", ".join(f"{kinds[k]} {k}" for k in sorted(kinds)) + ").",
        "",
    ]
    titles = {
        "bootstrap": "Bootstrap", "foundation": "Foundation", "platform": "Platform", "observability": "Observability (lab roots)",
        "applications": "Applications (artifact builds and deployment roots)", "docs": "Documentation",
    }
    for layer in ["bootstrap", "foundation", "platform", "observability", "applications", "docs"]:
        if layer not in by_layer:
            continue
        lines += [f"## {titles[layer]}", "",
                  "| Component | Kind | Owner directory | State key | Produces | Consumes | Optional consumes | Depends on | Profiles | Code present |",
                  "|---|---|---|---|---|---|---|---|---|---|"]
        for comp in by_layer[layer]:
            cid = comp["id"]
            kind = comp["kind"]
            if kind == "artifact":
                art = comp.get("artifact") or {}
                kind = f"artifact ({art.get('type')}" + (f" + {', '.join(art.get('also') or [])}" if art.get("also") else "") + ")"
            state = f"`<env>/{cid}.tfstate`" if comp["kind"] == "terraform" else "-"
            if comp.get("pipeline") == "manual":
                state += " (local first, then migrated)"
            deps = sorted({producers[c] for c in comp.get("consumes") or [] if c in producers} | set(comp.get("depends_on") or []))
            deps += [a for a in comp.get("artifacts") or []]
            if comp.get("after_deployments"):
                deps.append("(after all selected deploy-*)")
            optional = [c for c in comp.get("optional_consumes") or [] if c not in (comp.get("consumes") or [])]
            path = comp["path"]
            link = f"[`{path}/`](../../{path})"
            extra = []
            if comp.get("pipeline") == "manual":
                extra.append("pipeline: manual")
            if comp.get("discovers_resources"):
                extra.append("discovers resources from every enabled contract")
            kind_cell = kind + (f" - {'; '.join(extra)}" if extra else "")
            lines.append(
                f"| `{cid}` | {esc(kind_cell)} | {link} | {state} | {code_list(comp.get('produces'))} | {code_list(comp.get('consumes'))} | "
                f"{code_list(optional)} | {code_list(deps)} | {', '.join(sorted(profiles.get(cid, []))) or '-'} | {root_files_present(comp)} |"
            )
        lines.append("")
    lines += [
        "## Regenerate",
        "",
        "```bash",
        "python3 tools/docs/generate.py          # after editing catalog/components.yaml or a profile",
        "python3 tools/docs/generate.py --check  # CI-style staleness check",
        "python3 -m tools.changeset graph        # registry valid + acyclic, dependency layers",
        "```",
        "",
    ]
    return "\n".join(lines)


# ----------------------------------------------------------------------------------- architecture matrix
def _workload_service(w: str) -> str:
    return w.split(" ")[0].strip()


def data_for(workloads: list[str], databases: dict) -> list[str]:
    out = []
    for w in workloads:
        svc = _workload_service(w)
        for db_id, d in databases.items():
            owners = [d.get("owner", "")] + list(d.get("also") or [])
            for o in owners:
                o_svc = str(o).split(" ")[0]
                if not o_svc or o_svc == "none":
                    continue
                if svc.endswith("*") and o_svc.startswith(svc.rstrip("*")):
                    continue  # wildcard adapters: summarised below
                if o_svc == svc:
                    out.append(f"{db_id} ({d.get('boundary', '')})")
        if svc.endswith("*"):
            out.append("one database family per adapter instance (see Databases below)")
    return sorted(set(out))


def render_architecture_matrix() -> str:
    m = load("catalog/architecture-matrix.yaml")
    tel = load("catalog/telemetry-capabilities.yaml")["compute"]
    sup = load("tools/docs/architecture-matrix-supplement.yaml")["architectures"]
    dbs = m["databases"]
    lines = [
        GENERATED,
        "",
        "# Architecture deployment matrix",
        "",
        "Rendered from [`catalog/architecture-matrix.yaml`](../../catalog/architecture-matrix.yaml) (deliberate",
        "architecture-to-workload mapping, no compute x database Cartesian product), the telemetry paths of",
        "[`catalog/telemetry-capabilities.yaml`](../../catalog/telemetry-capabilities.yaml) and, for columns the catalog leaves",
        "empty, [`tools/docs/architecture-matrix-supplement.yaml`](../../tools/docs/architecture-matrix-supplement.yaml)",
        "whose values are taken from the deployment-root READMEs (marked with a dagger, source linked per row).",
        "",
        "Nothing in this table has been deployed: the smoke and rollback procedures are implemented in code",
        "(`applications/deployments/scripts/*.sh`, `tools/smoke/smoke.py`) but have not run against Azure.",
        "",
        "## Messaging topology",
        "",
        "| Entity | Name | Consumer | Purpose |",
        "|---|---|---|---|",
    ]
    sb = m["messaging"]["service_bus"]
    for name, sub in sb["subscriptions"].items():
        lines.append(f"| subscription of topic `{sb['topic']}` | `{name}` | {esc(sub['consumer'])} | {esc(sub['purpose'])} |")
    for name, q in sb["queues"].items():
        lines.append(f"| queue | `{name}` | {esc(q['consumer'])} | producers: {esc(', '.join(q.get('producers') or []))} |")
    lines += [
        "",
        "## Compute architectures",
        "",
        "| Architecture | Workloads | Deployment root | Artifact | Runtime configuration | Data dependency | Logs | Traces / metrics | Smoke test | Rollback |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for arch, a in m["architectures"].items():
        s = sup.get(arch, {})
        t = (tel.get(arch) or {}).get("signals", {})
        dep = a.get("deployment")
        dep = dep if isinstance(dep, list) else ([dep] if dep else [])
        dep_cell = ", ".join(f"`{d}`" for d in dep) or "-"

        def col(key: str) -> str:
            if a.get(key):
                return esc(a[key])
            if s.get(key):
                return esc(s[key]) + " &dagger;"
            return "not specified"

        data = esc(a["data"]) if a.get("data") else esc("; ".join(data_for(a.get("workloads") or [], dbs)) or "none")
        logs = esc((t.get("app_logs") or {}).get("method", "-"))
        traces = esc((t.get("traces") or {}).get("method", "-"))
        name = arch
        if a.get("status_default"):
            name += f" (default: {a['status_default']})"
        if a.get("note"):
            name += f" - {a['note']}"
        src = s.get("source")
        rollback = col("rollback")
        if src:
            rollback += f" ([src](../../{src}))"
        lines.append(
            f"| `{esc(name)}` | {esc(', '.join(a.get('workloads') or []))} | {dep_cell} | {col('artifact')} | {col('runtime_config')} | "
            f"{data} | {logs} | {traces} | {col('smoke')} | {rollback} |"
        )
    lines += [
        "",
        "## Databases (owner service and data boundary)",
        "",
        "| Database catalog entry | Owner | Boundary | Also used by | Default |",
        "|---|---|---|---|---|",
    ]
    for db_id, d in dbs.items():
        lines.append(f"| `{db_id}` | {esc(d.get('owner'))} | {esc(d.get('boundary', '-'))} | {esc(', '.join(d.get('also') or [])) or '-'} | {esc(d.get('default', 'per profile'))} |")
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------------------- alert runbooks
SECTION_INDEX = "../alert-response.md"


def render_alert_runbooks() -> dict[str, str]:
    pages: dict[str, str] = {}
    rendered = sorted(glob.glob(str(REPO / f"observability/onboarding/rendered/{ENV}/*.json")))
    index = [GENERATED, "", "# Alert runbooks per service", "",
             f"One page per service rendered from `observability/onboarding/rendered/{ENV}/*.json`. Each monitor message links to",
             "`<runbook_url>#<section>`; the anchors on these pages match those sections, and each section points to the shared",
             f"procedure in [alert-response.md]({SECTION_INDEX}).",
             "",
             "> The lab manifests (`observability/onboarding/<env>/*.yaml`) currently set `runbook_url` to",
             "> `https://runbooks.example.com/enterprise-hello/<service>` (a placeholder host). To make monitor links resolve to",
             "> these pages, the observability owner must point `metadata.runbook_url` at the published location of this",
             "> directory (see [known limitations](../../known-limitations.md#documentation-and-links)).",
             "",
             "| Service | Team | Runbook sections |", "|---|---|---|"]
    for f in rendered:
        d = json.loads(Path(f).read_text())
        svc = d.get("service") or Path(f).stem
        md = d.get("metadata") or {}
        monitors = d.get("monitors") or []
        if isinstance(monitors, dict):
            monitors = [dict(v, key=k) for k, v in monitors.items()]
        slos = d.get("slos") or []
        sections: dict[str, list[dict]] = defaultdict(list)
        for mon in monitors:
            url = mon.get("runbook_url") or ""
            sec = url.split("#", 1)[1] if "#" in url else mon.get("runbook_section", "")
            if sec:
                sections[sec].append(mon)
        raw = Path(f).read_text()
        base = md.get("runbook_url") or ""
        if base:
            for sec in set(re.findall(re.escape(base) + r"#([a-z0-9-]+)", raw)):
                sections.setdefault(sec, [])
        for slo in slos:
            for br in slo.get("burn_rate_alerts") or []:
                url = br.get("runbook_url") or ""
                if "#" in url:
                    sections[url.split("#", 1)[1]].append(dict(br, key=f"slo:{slo.get('name')}", type="slo alert"))
        team = md.get("team") or d.get("team") or "-"
        lines = [GENERATED, "", f"# Alert runbook: {svc}", "",
                 f"Service `{svc}` - team `{team}`, owner {md.get('owner') or d.get('owner') or '-'}, tier `{md.get('tier') or d.get('tier') or '-'}`,",
                 f"architecture `{(d.get('spec') or {}).get('architecture') or d.get('architecture') or '-'}`. Source: `observability/onboarding/{ENV}/{Path(f).stem}.yaml`",
                 f"(rendered `observability/onboarding/rendered/{ENV}/{Path(f).name}`).", "",
                 "Before acting on any no-data alert, check the telemetry pipeline canary ([telemetry-pipeline](telemetry-pipeline.md#pipeline-canary)):",
                 "a broken pipeline looks like silence.", ""]
        for sec in sorted(sections):
            lines += [f"## {sec}", "", f"Procedure: [alert-response.md#{sec}]({SECTION_INDEX}#{sec})", ""]
            mons = sections[sec]
            if mons:
                lines += ["| Monitor key | Name | Type | Severity |", "|---|---|---|---|"]
                for mon in sorted(mons, key=lambda x: str(x.get("key"))):
                    lines.append(f"| `{esc(mon.get('key'))}` | {esc(mon.get('name'))} | {esc(mon.get('type'))} | {esc(mon.get('severity') or mon.get('priority') or '-')} |")
                lines.append("")
            elif sec.startswith("slo"):
                lines += [f"SLO burn-rate alerts ({len(slos)} SLO(s) declared for this service).", ""]
        pages[f"docs/runbooks/alerts/{svc}.md"] = "\n".join(lines)
        index.append(f"| [{svc}]({svc}.md) | `{team}` | {', '.join(f'[{s}]({svc}.md#{s})' for s in sorted(sections))} |")
    index.append("")
    pages["docs/runbooks/alerts/README.md"] = "\n".join(index)
    return pages


# --------------------------------------------------------------------------------------- README status
def render_status_block() -> str:
    entries = []
    for f in sorted((REPO / "catalog/services").glob("*.yaml")):
        entries += yaml.safe_load(f.read_text())["services"]
    impl = Counter(e["status"]["implementation"] for e in entries)
    live = Counter(e["status"].get("live_validation", "not-run") for e in entries)
    nonga = sum(1 for e in entries if e["lifecycle"]["status"] != "ga")
    comps = load("catalog/components.yaml")["components"]
    kinds = Counter(c["kind"] for c in comps)
    layers = Counter(c["layer"] for c in comps)
    lines = [
        "<!-- BEGIN STATUS (generated by tools/docs/generate.py) -->",
        "| Catalog | Total | implemented | disabled | blocked | cataloged | live validation |",
        "|---|---:|---:|---:|---:|---:|---|",
        f"| Azure services (`catalog/services/*.yaml`) | {len(entries)} | {impl['implemented']} | {impl['disabled']} | {impl['blocked']} | {impl['cataloged']} | "
        + ", ".join(f"{k}: {v}" for k, v in sorted(live.items())) + " |",
        "",
        f"Components in `catalog/components.yaml`: **{len(comps)}** ({', '.join(f'{v} {k}' for k, v in sorted(kinds.items()))}; "
        + ", ".join(f"{v} {k}" for k, v in sorted(layers.items())) + f"). Non-GA lifecycle entries in the service catalog: {nonga}.",
        "<!-- END STATUS -->",
    ]
    return "\n".join(lines)


def outputs() -> dict[str, str]:
    out = {
        "docs/guides/component-ownership.md": render_component_ownership(),
        "docs/guides/architecture-deployment-matrix.md": render_architecture_matrix(),
    }
    out.update(render_alert_runbooks())
    readme = (REPO / "README.md")
    if readme.exists():
        text = readme.read_text()
        block = render_status_block()
        new = re.sub(r"<!-- BEGIN STATUS.*?<!-- END STATUS -->", lambda _: block, text, flags=re.S)
        out["README.md"] = new
    return {k: (v if v.endswith("\n") else v + "\n") for k, v in out.items()}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail when a committed output differs")
    args = ap.parse_args(argv)
    stale = []
    files = outputs()
    for rel, content in files.items():
        p = REPO / rel
        if args.check:
            if not p.exists() or p.read_text() != content:
                stale.append(rel)
        else:
            p.parent.mkdir(parents=True, exist_ok=True)
            if not p.exists() or p.read_text() != content:
                p.write_text(content)
                print(f"wrote {rel}")
    if args.check:
        alerts_dir = REPO / "docs/runbooks/alerts"
        for p in alerts_dir.glob("*.md"):
            rel = str(p.relative_to(REPO))
            if rel not in files:
                stale.append(f"{rel} (orphan)")
        for s in stale:
            print(f"STALE: {s}")
        return 1 if stale else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
