"""Chart-rendering test of modules/kubernetes (no cluster): the layered values the module passes to helm_release.datadog
([values/base.yaml, fleet layer, values_overrides...]) rendered with the REAL datadog chart (pinned version of the
module's charts.datadog_version) and the module's post-renderer (postrender/dsv-fetch-init.sh).

Checks the ONE secret path (ADR-0001 section 14): node Agent, Cluster Agent and cluster-checks runners all get the
dsv-fetch-install init container (dsv-fetch image -> in-memory emptyDir, uid 0, mode 0500 by `dsv-fetch install`), the
secret backend env (DD_SECRET_BACKEND_COMMAND=/opt/dsv-fetch/dsv-fetch agent-backend, generated by the chart) next to
the chart's own DD_API_KEY without duplicate entries (none overrides another), the DSV_* env and workload identity; the chart Secret holds only ENC[dsv://...]; the
Agent version is the fleet-policy pin.

Layers come from `terraform console` in the module directory (TF_DATA_DIR in a temp dir). Chart: DATADOG_CHART_TGZ
(path to datadog-<version>.tgz) or `helm pull` from helm.datadoghq.com. Skipped without terraform / helm / chart, or
with SKIP_TERRAFORM_TESTS=1.
"""

from __future__ import annotations

import base64
import json
import os
import re
import shutil
import subprocess
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parents[3]
MODULE = REPO / "observability" / "modules" / "kubernetes"
POSTRENDER = MODULE / "postrender" / "dsv-fetch-init.sh"
TERRAFORM = os.environ.get("TERRAFORM_BIN") or shutil.which("terraform")
HELM = os.environ.get("HELM_BIN") or shutil.which("helm")
FETCH_IMAGE = "ehacr.azurecr.io/dsv-fetch@sha256:" + "3" * 64
API_REF = "dsv://eh/dev/datadog-api-key#value"
AGENT_ID = "66666666-6666-6666-6666-666666666666"
CCR_ID = "77777777-7777-7777-7777-777777777777"

pytestmark = pytest.mark.skipif(not TERRAFORM or not HELM or os.environ.get("SKIP_TERRAFORM_TESTS") == "1",
                                reason="terraform / helm not installed or SKIP_TERRAFORM_TESTS=1")

BASE_VARS = {
    "cluster_name": "aks-eh-dev",
    "datadog": {"site": "datadoghq.eu", "env": "dev"},
    "dsv": {"api_key_ref": API_REF, "tenant": "contoso", "fetch_image": FETCH_IMAGE,
            "identity_client_id": AGENT_ID, "cluster_checks_identity_client_id": CCR_ID},
    "op_logs_url": "http://opw.internal:8282",
    "cluster_checks": {"postgres.yaml": "cluster_check: true\ninit_config: {}\ninstances:\n  - host: psql-eh-dev.postgres.database.azure.com\n"
                                        "    dbm: true\n    password: ENC[dsv://eh/dev/dbm-postgres-password#value]\n"},
}


def _run(cmd, **kw) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, timeout=600, **kw)


def _module_versions() -> tuple[str, str]:
    """(datadog chart version default, fleet policy agent.version)."""
    chart = re.search(r'datadog_version\s*=\s*optional\(string,\s*"([0-9.]+)"\)', (MODULE / "variables.tf").read_text()).group(1)
    fleet = yaml.safe_load((REPO / "observability" / "config" / "fleet-policy.yaml").read_text())
    return chart, fleet["agent"]["version"]


@pytest.fixture(scope="module")
def chart(tmp_path_factory) -> Path:
    version, _ = _module_versions()
    env_tgz = os.environ.get("DATADOG_CHART_TGZ")
    if env_tgz:
        return Path(env_tgz)
    d = tmp_path_factory.mktemp("chart")
    res = _run([HELM, "pull", "datadog", "--repo", "https://helm.datadoghq.com", "--version", version, "-d", str(d)])
    if res.returncode != 0:
        pytest.skip(f"datadog chart {version} not available (set DATADOG_CHART_TGZ): {res.stderr[-300:]}")
    return d / f"datadog-{version}.tgz"


@pytest.fixture(scope="module")
def tf_env(tmp_path_factory) -> dict:
    env = {**os.environ, "TF_DATA_DIR": str(tmp_path_factory.mktemp("tfdata")), "TF_IN_AUTOMATION": "1"}
    init = _run([TERRAFORM, "init", "-backend=false", "-input=false", "-lockfile=readonly"], cwd=MODULE, env=env)
    if init.returncode != 0:
        pytest.skip("terraform init failed (providers unavailable): " + init.stderr[-300:])
    return env


def _layers(tf_env: dict, tmp: Path, extra: dict | None = None) -> tuple[list[str], list[str]]:
    varfile = tmp / "vars.tfvars.json"
    varfile.write_text(json.dumps({**BASE_VARS, **(extra or {})}))
    expr = ('jsonencode({v = local.datadog_values, a = ["${path.module}/postrender/dsv-fetch-init.sh", "--image", '
            'var.dsv.fetch_image, "--expect", tostring(local.backend_workloads)]})')
    res = _run([TERRAFORM, "console", f"-var-file={varfile}"], cwd=MODULE, env=tf_env, input=expr)
    assert res.returncode == 0, res.stderr[-3000:]
    out = json.loads(json.loads(res.stdout.strip()))
    return out["v"], out["a"]


def _render(chart: Path, tmp: Path, layers: list[str], args: list[str]) -> list[dict]:
    files = []
    for i, doc in enumerate(layers):
        f = tmp / f"layer{i}.yaml"
        f.write_text(doc)
        files += ["-f", str(f)]
    kube = yaml.safe_load((REPO / "versions.yaml").read_text())["kubernetes"]["aks_default_version"]
    tpl = _run([HELM, "template", "datadog", str(chart), "-n", "datadog", "--kube-version", f"{kube}.0", *files])
    assert tpl.returncode == 0, tpl.stderr[-3000:]
    # same protocol the helm provider uses: rendered manifests on stdin, post-rendered on stdout
    pr = _run(["sh", str(MODULE / args[0].removeprefix("./")), *args[1:]], input=tpl.stdout)
    assert pr.returncode == 0, pr.stderr
    return [d for d in yaml.safe_load_all(pr.stdout) if d]


@pytest.fixture(scope="module")
def rendered(chart, tf_env, tmp_path_factory):
    tmp = tmp_path_factory.mktemp("render")
    layers, args = _layers(tf_env, tmp)
    return {"layers": layers, "args": args, "docs": _render(chart, tmp, layers, args)}


def _workloads(docs: list[dict]) -> dict[str, dict]:
    return {d["metadata"]["name"]: d for d in docs if d["kind"] in ("DaemonSet", "Deployment") and d["metadata"]["name"].startswith("datadog")}


def _env(c: dict) -> list[dict]:
    return c.get("env", [])


def test_layers_order_and_no_secret(rendered):
    layers = rendered["layers"]
    assert layers[0] == (MODULE / "values" / "base.yaml").read_text(), "layer 0 = values/base.yaml verbatim"
    fleet = yaml.safe_load(layers[1])
    assert fleet["datadog"]["apiKey"] == f"ENC[{API_REF}]" and "apiKeyExistingSecret" not in fleet["datadog"]
    assert rendered["args"][1:] == ["--image", FETCH_IMAGE, "--expect", "3"]


def test_every_datadog_workload_gets_the_dsv_fetch_install_init_container(rendered):
    wl = _workloads(rendered["docs"])
    assert set(wl) == {"datadog", "datadog-cluster-agent", "datadog-clusterchecks"}
    for name, d in wl.items():
        spec = d["spec"]["template"]["spec"]
        init = spec["initContainers"][0]
        assert init["name"] == "dsv-fetch-install" and init["image"] == FETCH_IMAGE, name
        assert init["command"] == ["/opt/dsv-fetch/dsv-fetch", "install", "--dest", "/dsv-fetch-out/dsv-fetch"], name
        sc = init["securityContext"]
        assert sc["runAsUser"] == 0 and sc["readOnlyRootFilesystem"] and not sc["allowPrivilegeEscalation"] and sc["capabilities"]["drop"] == ["ALL"], name
        vol = {v["name"]: v for v in spec["volumes"]}["dsv-fetch"]
        assert vol["emptyDir"]["medium"] == "Memory", name
        assert init["volumeMounts"] == [{"name": "dsv-fetch", "mountPath": "/dsv-fetch-out"}], name


def test_secret_backend_env_and_mount_in_every_agent_container(rendered):
    wl = _workloads(rendered["docs"])
    checked = []
    for name, d in wl.items():
        for c in d["spec"]["template"]["spec"]["containers"]:
            env = _env(c)
            names = [e["name"] for e in env]
            if "DD_API_KEY" not in names:
                continue
            checked.append(f"{name}/{c['name']}")
            dupes = sorted({n for n in names if names.count(n) > 1})
            assert not dupes, f"{name}/{c['name']}: duplicate env {dupes}"
            ev = {e["name"]: e for e in env}
            assert ev["DD_SECRET_BACKEND_COMMAND"]["value"] == "/opt/dsv-fetch/dsv-fetch", f"{name}/{c['name']}"
            assert ev["DD_SECRET_BACKEND_ARGUMENTS"]["value"] == "agent-backend"
            # chart-generated DD_API_KEY / DD_SECRET_BACKEND_* + our DSV_* entries: each exactly once (no duplicate
            # that a later entry would win), DD_API_KEY from the chart Secret (= the ENC[] reference)
            assert ev["DD_API_KEY"]["valueFrom"]["secretKeyRef"]["name"] == "datadog"
            assert ev["DSV_BASE_URL"]["value"] == "https://contoso.secretsvaultcloud.com/v1" and ev["DSV_AUTH"]["value"] == "azure", f"{name}/{c['name']}"
            mounts = {m["name"]: m for m in c.get("volumeMounts", [])}
            assert mounts["dsv-fetch"]["mountPath"] == "/opt/dsv-fetch" and mounts["dsv-fetch"]["readOnly"], f"{name}/{c['name']}"
    for must in ("datadog/agent", "datadog/trace-agent", "datadog-cluster-agent/cluster-agent", "datadog-clusterchecks/agent"):
        assert must in checked, (must, checked)
    blob = json.dumps(rendered["docs"])
    assert '"name": "DD_SECRET_BACKEND_COMMAND", "value": ""' not in blob, "no secret-backend opt-out for the Cluster Agent"


def test_chart_secret_holds_only_the_reference(rendered):
    secrets = {d["metadata"]["name"]: d for d in rendered["docs"] if d["kind"] == "Secret"}
    assert base64.b64decode(secrets["datadog"]["data"]["api-key"]).decode() == f"ENC[{API_REF}]"
    confd = next(d for d in rendered["docs"] if d["kind"] == "ConfigMap" and d["metadata"]["name"] == "datadog-cluster-agent-confd")
    assert "ENC[dsv://eh/dev/dbm-postgres-password#value]" in confd["data"]["postgres.yaml"] and "cluster_check: true" in confd["data"]["postgres.yaml"]


def test_workload_identity_per_service_account(rendered):
    sas = {d["metadata"]["name"]: d.get("metadata", {}).get("annotations", {}) for d in rendered["docs"] if d["kind"] == "ServiceAccount"}
    assert sas["datadog"]["azure.workload.identity/client-id"] == AGENT_ID
    assert sas["datadog-cluster-agent"]["azure.workload.identity/client-id"] == AGENT_ID
    assert sas["datadog-cluster-checks"]["azure.workload.identity/client-id"] == CCR_ID
    for name, d in _workloads(rendered["docs"]).items():
        assert d["spec"]["template"]["metadata"]["labels"]["azure.workload.identity/use"] == "true", name


def test_agent_version_is_the_single_fleet_pin(rendered):
    _, pin = _module_versions()
    assert yaml.safe_load((REPO / "versions.yaml").read_text())["images"]["datadog_agent"].endswith(f":{pin}")
    for name, d in _workloads(rendered["docs"]).items():
        for c in d["spec"]["template"]["spec"]["containers"]:
            if "datadog" in c["image"] and "dsv-fetch" not in c["image"]:
                assert c["image"].endswith(f":{pin}"), (name, c["image"])


def test_overrides_apply_last_and_runner_count(chart, tf_env, tmp_path):
    override = "clusterAgent:\n  replicas: 2\nagents:\n  containers:\n    agent:\n      resources: {limits: {memory: 1Gi}}\n"
    layers, args = _layers(tf_env, tmp_path, {"values_overrides": [override], "cluster_checks": {},
                                              "features": {"cluster_checks_runner": False}})
    assert args[-1] == "2"
    wl = _workloads(_render(chart, tmp_path, layers, args))
    assert "datadog-clusterchecks" not in wl
    assert wl["datadog-cluster-agent"]["spec"]["replicas"] == 2
    agent = next(c for c in wl["datadog"]["spec"]["template"]["spec"]["containers"] if c["name"] == "agent")
    assert agent["resources"]["limits"]["memory"] == "1Gi" and agent["resources"]["requests"]["memory"] == "256Mi"


def test_postrender_fails_closed(rendered, tmp_path):
    manifest = "---\n# Source: datadog/templates/daemonset.yaml\nkind: DaemonSet\nspec:\n  template:\n    spec:\n      initContainers:\n      - name: x\n"
    ok = _run(["sh", str(POSTRENDER), "--image", FETCH_IMAGE, "--expect", "1"], input=manifest)
    assert ok.returncode == 0 and "dsv-fetch-install" in ok.stdout
    wrong_count = _run(["sh", str(POSTRENDER), "--image", FETCH_IMAGE, "--expect", "3"], input=manifest)
    assert wrong_count.returncode != 0 and "expected 3" in wrong_count.stderr
    tag_only = _run(["sh", str(POSTRENDER), "--image", "ehacr.azurecr.io/dsv-fetch:2.0.0", "--expect", "1"], input=manifest)
    assert tag_only.returncode == 2
