"""Read-only Terraform provider mirror shared by parallel `terraform init` processes.

A shared TF_PLUGIN_CACHE_DIR is not concurrency safe (Terraform documents it; parallel inits race on the same
executable: "text file busy"). Instead the job populates ONE filesystem mirror up front (`terraform providers
mirror` for every provider version pinned in the .terraform.lock.hcl files of the selected roots; restored from
Cache@2 keyed by the hash of all lock files) and every init installs from it through a CLI config with
`provider_installation { filesystem_mirror {...} }` and no plugin cache: each root gets its own copy in
.terraform/, nothing shared is written.

    python3 -m tools.ci tf-mirror --mirror <dir> [--roots a,b] [--config-out <file>]   # prints TF_CLI_CONFIG_FILE
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from pathlib import Path
from typing import Iterable, List, Optional, Set, Tuple

PROVIDER_RE = re.compile(r'provider\s+"(?P<addr>[^"]+)"\s*\{[^}]*?version\s*=\s*"(?P<ver>[^"]+)"', re.S)


def lock_providers(repo: Path, roots: Optional[Iterable[str]] = None) -> Set[Tuple[str, str]]:
    files = [repo / r / ".terraform.lock.hcl" for r in roots] if roots else sorted(repo.glob("**/.terraform.lock.hcl"))
    out = set()
    for f in files:
        if f.exists() and "/.terraform/" not in f.as_posix():
            out |= {(m["addr"], m["ver"]) for m in PROVIDER_RE.finditer(f.read_text())}
    return out


def present(mirror: Path, addr: str, version: str) -> bool:
    host_ns_type = addr.split("/")
    d = mirror.joinpath(*host_ns_type)
    if (d / version).is_dir():                         # unpacked layout (also the plugin-cache layout)
        return True
    return any(d.glob(f"terraform-provider-{host_ns_type[-1]}_{version}_*.zip"))   # packed layout


def populate(mirror: Path, providers: Set[Tuple[str, str]], runner=subprocess.run) -> List[str]:
    missing = sorted(p for p in providers if not present(mirror, *p))
    if not missing:
        return []
    mirror.mkdir(parents=True, exist_ok=True)
    for addr, ver in missing:          # one config per provider version (a config pins one version per provider)
        with tempfile.TemporaryDirectory() as tmp:
            local = addr.split("/")[-1]
            Path(tmp, "main.tf").write_text(
                'terraform {\n  required_providers {\n'
                f'    {local} = {{\n      source  = "{addr}"\n      version = "{ver}"\n    }}\n'
                '  }\n}\n')
            p = runner(["terraform", f"-chdir={tmp}", "providers", "mirror", "-platform=linux_amd64", str(mirror)],
                       capture_output=True, text=True)
            if p.returncode != 0:
                raise RuntimeError(f"terraform providers mirror {addr} {ver} failed: {p.stderr[-500:]}")
    return [f"{a} {v}" for a, v in missing]


def cli_config(mirror: Path, dest: Path) -> Path:
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        "# generated by tools/ci/tfmirror.py: install every provider from the read-only job mirror\n"
        "provider_installation {\n"
        f'  filesystem_mirror {{\n    path    = "{mirror.resolve().as_posix()}"\n    include = ["*/*/*"]\n  }}\n'
        '  direct {\n    exclude = ["*/*/*"]\n  }\n'
        "}\n")
    return dest
