#!/usr/bin/env python3
"""Render the human-readable coverage matrices from the machine-readable catalog.

Outputs (deterministic; no timestamps other than catalog verified_on):
  docs/coverage/coverage-matrix.md              one table per category from catalog/services/*.yaml
  docs/coverage/telemetry-capability-matrix.md  from catalog/telemetry-capabilities.yaml

Usage:
  python3 tools/catalog/render_coverage.py            # write files
  python3 tools/catalog/render_coverage.py --check    # exit 1 if files are missing or out of date
  python3 tools/catalog/render_coverage.py --out DIR  # write to another directory
"""
from __future__ import annotations

import argparse
import pathlib
import sys
from collections import Counter

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from catalog_lib import (  # noqa: E402
    COVERAGE_DIR, GAPS_PATH, REPO_ROOT, TELEMETRY_PATH, all_entries, load_service_files, load_yaml,
)

CATEGORY_TITLES = [
    ("database", "Databases"),
    ("analytics", "Analytics"),
    ("adjacent-data", "Adjacent data services"),
    ("compute", "Compute"),
    ("serverless", "Serverless"),
    ("messaging", "Messaging"),
    ("platform-support", "Platform support"),
    ("partner", "Partner services (Azure Native Integrations / Oracle Database@Azure)"),
    ("fabric", "Microsoft Fabric (not ARM resources, except the capacity)"),
    ("specialized", "Specialized"),
]
SIG_ABBR = [("metrics", "M"), ("logs", "L"), ("traces", "T"), ("rum", "RUM"), ("profiling", "Prof")]
SUP = {"yes": "yes", "no": "no", "partial": "partial", "n/a": "-"}
GENERATED = "<!-- GENERATED by tools/catalog/render_coverage.py from catalog/*.yaml - do not edit by hand -->"


def esc(text) -> str:
    if text is None:
        return ""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def link_refs(refs: list[str]) -> str:
    return " ".join(f"[{i}]({u})" for i, u in enumerate(refs, 1))


def iac_cell(iac: dict) -> str:
    parts = [f"`{r}`" for r in iac.get("terraform_resources") or []]
    parts += [f"azapi `{a['type']}@{a['api_version']}`" for a in iac.get("azapi") or []]
    return "<br>".join(parts) if parts else "none (not IaC-deployable)"


def signals_cell(tele: dict) -> str:
    sig = tele.get("signals") or {}
    return " ".join(f"{abbr}:{SUP.get(sig.get(k, {}).get('supported'), '?')}" for k, abbr in SIG_ABBR)


def cost_cell(cost: dict) -> str:
    usd = cost.get("approx_monthly_usd_default")
    amount = "n/a" if usd is None else f"~${usd:,.0f}/mo"
    return f"{cost.get('profile')} ({amount})"


def lifecycle_cell(lc: dict) -> str:
    out = lc.get("status", "?")
    if lc.get("retirement_date"):
        out += f" ({lc['retirement_date']})"
    return out


def status_cell(st: dict) -> str:
    out = st.get("implementation", "?")
    if st.get("default_profiles"):
        out += f" [{', '.join(st['default_profiles'])}]"
    if st.get("blocked_reason"):
        out += f": {st['blocked_reason']}"
    return out


def render_coverage(docs: dict) -> str:
    entries = [e for _, e in all_entries(docs)]
    verified = sorted({d.get("verified_on") for d in docs.values() if d})
    lines = [GENERATED, "", "# Azure service coverage matrix", ""]
    lines += [
        f"Source: `catalog/services/*.yaml` (schema `catalog/schemas/service.schema.json`), facts verified {', '.join(verified)} "
        "against Microsoft Learn, docs.datadoghq.com and the azurerm 5.9.0 / azapi 2.13.0 provider schemas. "
        "Status vocabulary per ADR-0001 section 11. **Live validation is `not-run` for every entry: no Azure or Datadog "
        "credentials were available, so nothing has been deployed or verified.**",
        "",
        "Signals column: M = platform/app metrics, L = logs, T = traces, RUM = browser RUM, Prof = profiling "
        "(yes / partial / no / - = not applicable). DBM = Datadog Database Monitoring for that exact hosting variant. "
        "Cost is an approximate list-price estimate at lab defaults (see each entry's `cost.assumptions`).",
        "",
        "## Summary",
        "",
        "| Category | Entries | implemented | disabled | blocked | cataloged | non-GA lifecycle |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for cat, title in CATEGORY_TITLES:
        es = [e for e in entries if e["category"] == cat]
        if not es:
            continue
        c = Counter(e["status"]["implementation"] for e in es)
        nonga = sum(1 for e in es if e["lifecycle"]["status"] != "ga")
        lines.append(f"| {title} | {len(es)} | {c['implemented']} | {c['disabled']} | {c['blocked']} | {c['cataloged']} | {nonga} |")
    c = Counter(e["status"]["implementation"] for e in entries)
    lines.append(f"| **Total** | **{len(entries)}** | **{c['implemented']}** | **{c['disabled']}** | **{c['blocked']}** | **{c['cataloged']}** | "
                 f"**{sum(1 for e in entries if e['lifecycle']['status'] != 'ga')}** |")
    lines += ["", "## Lifecycle watch list (non-GA)", "",
              "| Service | Lifecycle | Retirement | Creation blocked from | Successor | Notes |", "|---|---|---|---|---|---|"]
    order = {"retired": 0, "retiring": 1, "not-recommended": 2, "legacy": 3, "preview": 4}
    for e in sorted((e for e in entries if e["lifecycle"]["status"] != "ga"),
                    key=lambda x: (order.get(x["lifecycle"]["status"], 9), x["id"])):
        lc = e["lifecycle"]
        lines.append(f"| {esc(e['display_name'])} (`{e['id']}`) | {lc['status']} | {lc.get('retirement_date', '')} | "
                     f"{lc.get('creation_blocked_from', '')} | {esc(lc.get('successor', ''))} | {esc(lc['notes'])} |")

    header = ("| Service | Variant | Lifecycle | IaC resource | Component | Workload | Signals | DBM | Cost | Implementation | Live validation | Refs |\n"
              "|---|---|---|---|---|---|---|---|---|---|---|---|")
    for cat, title in CATEGORY_TITLES:
        es = [e for e in entries if e["category"] == cat]
        if not es:
            continue
        lines += ["", f"## {title}", "", header]
        for e in es:
            sig = e["telemetry"]["signals"]
            dbm = sig.get("dbm", {})
            dbm_cell = SUP.get(dbm.get("supported"), "?")
            if dbm.get("supported") in ("yes", "partial", "no") and dbm.get("notes"):
                dbm_cell += f" - {dbm['notes']}"
            wl = e["workload"]
            workload = ", ".join(wl.get("exercised_by") or []) or "-"
            regions = e["availability"]["regions_checked"]
            region_flags = " ".join(f"{r}:{'Y' if v is True else 'N' if v is False else '?'}" for r, v in regions.items())
            variant = f"{esc(e['hosting_variant'])}<br><sub>{region_flags}</sub>"
            lines.append("| " + " | ".join([
                f"**{esc(e['display_name'])}**<br>`{e['id']}`",
                variant,
                esc(lifecycle_cell(e["lifecycle"])),
                iac_cell(e["iac"]),
                f"`{e['iac']['component']}`" if e["iac"].get("component") else "-",
                esc(workload),
                signals_cell(e["telemetry"]),
                esc(dbm_cell),
                esc(cost_cell(e["cost"])),
                esc(status_cell(e["status"])),
                e["status"]["live_validation"],
                link_refs(e["references"]),
            ]) + " |")

    gaps = (load_yaml(GAPS_PATH) or {}).get("gaps") or []
    lines += ["", "## Provider gaps (azurerm 5.9.0)", "",
              "From `catalog/provider-gaps.yaml`; AzAPI is allowed only for these.", "",
              "| Service | Resolution | ARM type@API version | Reason |", "|---|---|---|---|"]
    for g in gaps:
        types = "<br>".join(f"`{t['type']}@{t['api_version']}`" for t in g.get("arm_types") or []) or "-"
        lines.append(f"| `{g['service_id']}` | {g['resolution']} | {types} | {esc(g['reason'])} |")
    lines.append("")
    return "\n".join(lines)


def render_telemetry(doc: dict) -> str:
    lines = [GENERATED, "", "# Telemetry capability matrix", ""]
    lines += [esc(doc.get("description")), "", f"Verified {doc.get('verified_on')}. Each cell: support / method / owner component.", ""]
    sigs = doc.get("signals") or []

    def cell(s: dict) -> str:
        if not s:
            return "?"
        if s.get("supported") == "n/a":
            return "-"
        owner = f" <sub>({esc(s.get('owner'))})</sub>" if s.get("owner") else ""
        prefix = "" if s.get("supported") == "yes" else f"**{s.get('supported')}**: "
        return prefix + esc(s.get("method")) + owner

    lines += ["## Compute architectures", "", "| Architecture | " + " | ".join(sigs) + " |", "|---|" + "---|" * len(sigs)]
    for key, val in (doc.get("compute") or {}).items():
        lines.append(f"| `{key}` | " + " | ".join(cell(val["signals"].get(s)) for s in sigs) + " |")
    lines += ["", "### Duplicate prevention and Datadog limitations (compute)", "",
              "| Architecture | Signal | Duplicate prevention | Datadog limitation |", "|---|---|---|---|"]
    for key, val in (doc.get("compute") or {}).items():
        for s in sigs:
            sv = val["signals"].get(s) or {}
            if sv.get("supported") in ("yes", "partial"):
                lines.append(f"| `{key}` | {s} | {esc(sv.get('duplicate_prevention'))} | {esc(sv.get('datadog_limitation'))} |")
    dsigs = doc.get("database_signals") or []
    lines += ["", "## Database families", "", "| Database | " + " | ".join(dsigs) + " |", "|---|" + "---|" * len(dsigs)]
    for key, val in (doc.get("databases") or {}).items():
        lines.append(f"| `{key}` | " + " | ".join(cell(val["signals"].get(s)) for s in dsigs) + " |")
    lines += ["", "### Database Monitoring limitations", "", "| Database | DBM | Limitation |", "|---|---|---|"]
    for key, val in (doc.get("databases") or {}).items():
        d = val["signals"].get("dbm") or {}
        lines.append(f"| `{key}` | {d.get('supported')} | {esc(d.get('datadog_limitation'))} |")
    findings = doc.get("findings") or {}
    if findings:
        lines += ["", "## Verified findings", ""]
        for k, v in findings.items():
            if isinstance(v, dict):
                lines.append(f"- **{k}**")
                for k2, v2 in v.items():
                    lines.append(f"  - {k2}: {esc(v2)}")
            else:
                lines.append(f"- **{k}**: {esc(v)}")
    srcs = doc.get("sources") or {}
    if srcs:
        lines += ["", "## Sources", ""] + [f"- {k}: <{v}>" for k, v in srcs.items()]
    lines.append("")
    return "\n".join(lines)


def outputs() -> dict[str, str]:
    docs = load_service_files()
    return {
        "coverage-matrix.md": render_coverage(docs),
        "telemetry-capability-matrix.md": render_telemetry(load_yaml(TELEMETRY_PATH) or {}),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if rendered files differ from the committed ones")
    ap.add_argument("--out", type=pathlib.Path, default=COVERAGE_DIR)
    args = ap.parse_args(argv)
    try:
        rendered = outputs()
    except Exception as exc:  # noqa: BLE001 - surface any catalog load/render problem as a failure
        print(f"ERROR rendering coverage: {exc}", file=sys.stderr)
        return 1
    stale = []
    for name, text in rendered.items():
        path = args.out / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(str(path.relative_to(REPO_ROOT) if path.is_relative_to(REPO_ROOT) else path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path}")
    if stale:
        print("ERROR out-of-date (run python3 tools/catalog/render_coverage.py): " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
