#!/usr/bin/env python3
"""Verify that the DSV secret paths an environment needs exist - without reading or printing any value.

    python3 tools/secrets/check.py --env dev                 # required by the enabled components
    python3 tools/secrets/check.py --env dev --names fault-token,datadog-api-key
    python3 tools/secrets/check.py --env dev --strict        # generated secrets missing = error, not warning

Required set: tools/secrets/catalog.py (foundation/identity/secrets.yaml `required_by` of enabled components +
non-optional `secret_env` of enabled components). Each path is checked with the metadata-only describe call
(GET /v1/secrets/<path>::description) and, when that is forbidden, with a search (`list` permission); the data
endpoint is never called. Authentication: the caller's managed identity (pipelines: deploy agent, granted `list`
on the environment's paths by foundation-secrets).
Exit: 0 all present; 1 missing required operator secrets (or generated ones with --strict) or errors.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tools.secrets.catalog import load_catalogue, required  # noqa: E402
from tools.secrets.dsvlib import DsvClient, DsvError, base_url_from, load_env_settings  # noqa: E402


def check(client: DsvClient, base_path: str, names, catalogue, strict: bool = False):
    rows, errors, warnings = [], 0, 0
    listed, searched = None, False   # listed stays None when the search itself failed (=> unverifiable)
    for name in names:
        path = f"{base_path}/{name}"
        present, status = client.exists(path)
        if present is None and status == 403:
            if not searched:
                searched = True
                st, resp = client.request("GET", "secrets", query={"searchTerm": base_path})
                if st == 200:
                    listed = {d.get("path", "").strip("/") for d in (resp.get("data") or [])}
            present = (path in listed) if listed is not None else None
        meta = catalogue.get(name, {})
        generated = meta.get("source") == "generated"
        if present:
            state = "present"
        elif present is False:
            if generated and not strict:
                state, warnings = f"missing (generated by {meta.get('publisher')} on its next apply)", warnings + 1
            else:
                state, errors = "MISSING", errors + 1
        else:
            state, errors = f"UNVERIFIABLE (HTTP {status}: grant `list` to the checker)", errors + 1
        rows.append((name, path, state))
    return rows, errors, warnings


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--env", required=True)
    ap.add_argument("--names", help="comma separated secret names (default: required by enabled components)")
    ap.add_argument("--strict", action="store_true")
    ap.add_argument("--repo", default=".")
    args = ap.parse_args(argv)
    repo = Path(args.repo).resolve()
    try:
        settings = load_env_settings(repo, args.env)
        catalogue = load_catalogue(repo)
        need = {n: [] for n in args.names.split(",") if n} if args.names else required(repo, args.env)
        unknown = sorted(n for n in need if n not in catalogue)
        if unknown:
            print(f"ERROR: not in foundation/identity/secrets.yaml: {', '.join(unknown)}", file=sys.stderr)
            return 1
        client = DsvClient(base_url_from(settings))
        rows, errors, warnings = check(client, settings["base_path"], sorted(need), catalogue, args.strict)
    except DsvError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    width = max((len(r[0]) for r in rows), default=4)
    for name, path, state in rows:
        users = ",".join(need.get(name) or [])
        print(f"{name:<{width}}  {state:<10}  dsv://{path}#value" + (f"  (needed by {users})" if users else ""))
    print(f"{len(rows)} checked, {errors} error(s), {warnings} warning(s)")
    if errors:
        print("##vso[task.logissue type=error]DSV: required secret paths missing - see docs/runbooks/secret-rotation.md")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
